import { redirect } from "next/navigation";
import Link from "next/link";
import { ChevronLeft } from "lucide-react";
import { createServiceClient, getCurrentUser, hasAdminAccess } from "@/lib/supabase-server";
import { RfqQueueDashboard } from "./rfq-queue-dashboard";

export const dynamic = "force-dynamic";

/**
 * /rfq/queue — RFQ drafts queue. Abe reviews drafts generated by the
 * RFQ generator (sol_bulk action, auto_research, manual), edits them
 * if needed, and approves to send. Send queues to a daemon-side worker
 * that fires the actual EWS sendMail.
 */

async function getData() {
  const sb = createServiceClient();

  // Pull recent + active drafts (skip ancient cancelled/sent for default view)
  const { data: drafts } = await sb
    .from("rfq_drafts")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(500);

  const counts = {
    total: drafts?.length || 0,
    draft: drafts?.filter((r: any) => r.status === "draft").length || 0,
    pending_send: drafts?.filter((r: any) => r.status === "pending_send").length || 0,
    sending: drafts?.filter((r: any) => r.status === "sending").length || 0,
    sent: drafts?.filter((r: any) => r.status === "sent").length || 0,
    send_failed: drafts?.filter((r: any) => r.status === "send_failed").length || 0,
    cancelled: drafts?.filter((r: any) => r.status === "cancelled").length || 0,
  };

  return { drafts: drafts || [], counts };
}

export default async function RfqQueuePage() {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  if (!hasAdminAccess(user.profile?.role)) redirect("/settings");

  const data = await getData();
  return (
    <div className="p-4 md:p-8 max-w-7xl mx-auto">
      <div className="flex items-center gap-2 mb-4 text-sm text-muted">
        <Link href="/" className="hover:text-accent flex items-center gap-1">
          <ChevronLeft className="h-4 w-4" /> Home
        </Link>
        <span>/</span>
        <span className="text-foreground font-medium">RFQ Queue</span>
      </div>
      <RfqQueueDashboard {...data} />
    </div>
  );
}
