-- dbo.DELETED_OLD_ORDERS_OEOO_1  (5772 rows)
CREATE TABLE dbo.DELETED_OLD_ORDERS_OEOO_1 (
  p_id                 int NOT NULL,
  SALORD               varchar(6),
  ZERPAD3              varchar(3),
  ZERPAD4              varchar(2),
  ZERPAD5              varchar(1),
  RECTYP               varchar(1),
  CUSTMR               varchar(7),
  SALREP               varchar(2),
  DOCMNT               varchar(5),
  SHIVIA               varchar(3),
  ORDSCH               varchar(1),
  BOCOM                varchar(1),
  ACCBO                varchar(1),
  SHICOM               varchar(1),
  INVTO                varchar(1),
  SITYP                varchar(1),
  LASLIN               numeric(3,0),
  TAXLIC1              varchar(15),
  TAXLIC2              varchar(21),
  CUSTMRPO             varchar(12),
  WHSE                 varchar(2),
  MANDOC               varchar(8),
  CONTACT              numeric(12,0),
  ECORD                varchar(12),
  CLATRA               varchar(3),
  SALGRO               varchar(3),
  PROVNC               varchar(2),
  TERTRY               varchar(3),
  CURRNCY              varchar(4),
  FLYELG               varchar(1),
  CQUELG               varchar(1),
  LEVTYP               varchar(1),
  PRILEV               numeric(1,0),
  CONCON               varchar(1),
  SPECON               varchar(1),
  COMCON               varchar(1),
  FLYCON               varchar(1),
  QTYCON               varchar(1),
  CONSPE               varchar(1),
  SPESPE               varchar(1),
  COMSPE               varchar(1),
  FLYSPE               varchar(1),
  QTYSPE               varchar(1),
  PAYOFF               varchar(7),
  TRASHO               varchar(32),
  HELDBY               varchar(12),
  ORDTYP               varchar(1),
  REORDR               varchar(1),
  IMPORD               varchar(1),
  REVBY                varchar(12),
  PRIMARY KEY (p_id)
);