-- dbo.imported_and_deleted_orders_transfer_shipto  (29842 rows)
CREATE TABLE dbo.imported_and_deleted_orders_transfer_shipto (
  SALORD               char(6) NOT NULL,
  myCUSTMR             varchar(7),
  myCUSTMRPO           varchar(12),
  mySHIPTONAM          varchar(30),
  myADDR1              varchar(30),
  myADDR2              varchar(30),
  myPOSTAL             varchar(10),
  myADDR3              varchar(30),
  myPROVNC             varchar(2),
  myCOUNTR             varchar(20),
  myTELPHN             varchar(20),
  myFAX                varchar(20),
  mySALREP             char(2),
  QVN                  varchar(1),
  QVNTYPE1             varchar(20),
  SHIPFROM             varchar(200),
  QVNEMAIL1            varchar(200),
  QVNFAIL              varchar(200),
  QVNSUBJ              varchar(200),
  QVNMEMO              varchar(300),
  QVNSHIPN1            varchar(1),
  Mail_Innovations_Cost_Center varchar(20),
  USPS_Deliver_Confirmation bit,
  Mail_Innovations_Weight bit,
  myATTENTION          varchar(32)
);