-- dbo.temp_apvf  (3417 rows)
CREATE TABLE dbo.temp_apvf (
  VENDOR               varchar(6),
  VENDORNAM            varchar(40),
  ADDRSS1              varchar(40),
  ADDRSS2              varchar(40),
  ADDRSS3              varchar(40),
  POSTAL               varchar(10),
  CONTCT               varchar(30),
  TELPHN               varchar(20),
  FAX                  varchar(20),
  WATTS                varchar(20),
  GLACCT               varchar(8),
  NETAPTER             varchar(2),
  NUMDAYPAY            numeric(3,0),
  DISAPTER             varchar(2),
  NUMDAYDIS            numeric(3,0),
  DISPER               numeric(4,2),
  NETPURYTD            numeric(10,2),
  LASPURDAT            date,
  BANK                 varchar(1),
  CRECLA               varchar(2),
  DEFBRA               varchar(2),
  STATUS               varchar(1),
  PAYVENDOR            varchar(6),
  YTDNUMINV            numeric(8,0),
  TAXLIC1              varchar(15),
  TEN99                varchar(1)
);