-- dbo.temp_apih  (91638 rows)
CREATE TABLE dbo.temp_apih (
  VENDOR               varchar(6),
  INVOICE              varchar(9),
  LASTRA               numeric(2,0),
  INVDAT               date,
  DUEDAT               date,
  INVCAMT              numeric(10,2),
  PAIAMT               numeric(10,2),
  ENTTYP               varchar(1),
  SEPCHE               varchar(1),
  INVCBAN              varchar(1),
  DISDAT               date,
  DISAMT               numeric(10,2),
  DISTAK               numeric(10,2),
  LASLIN               numeric(3,0),
  MESSG                varchar(30),
  FREAMT               numeric(10,2),
  PAYVENDOR            varchar(6),
  CANFLG               varchar(1),
  POSDAT               date,
  BALFORINVC           varchar(1),
  PAYBAN               varchar(1),
  LASCHE               varchar(6),
  RECACCAMT            numeric(10,2),
  BRANCH               varchar(2),
  CRECLA               varchar(2),
  CURRNCY              numeric(7,6),
  DOMINVAMT            numeric(11,2),
  DOMTOTPAI            numeric(11,2),
  DOMDIS               numeric(11,2),
  DOMDISTAK            numeric(11,2),
  DOMFRE               numeric(11,2),
  HOLD                 varchar(4)
);