-- dbo.temp_pooo1  (1882 rows)
CREATE TABLE dbo.temp_pooo1 (
  PURORD               varchar(6),
  ZERLIN               varchar(3),
  ZERPAD               varchar(1),
  RECTYP               varchar(1),
  SUPPLR               varchar(6),
  PURDAT               date,
  PRTFLA               varchar(1),
  FRETER               varchar(2),
  TOTVOL               numeric(11,0),
  SHIPTO               varchar(6),
  WHSE                 varchar(2),
  TERMDES              varchar(15),
  LASLIN               numeric(3,0),
  REQDAT               date,
  SHIVIA               varchar(15),
  FOB                  varchar(15),
  CURRNCY              varchar(4),
  RECPT                varchar(5),
  OUTAMT               numeric(12,2),
  TOTWGHT              numeric(9,2),
  BUYER                varchar(1),
  CANDAT               date,
  COMMNT               varchar(120),
  RECFLA               varchar(1),
  TYPE                 varchar(1),
  CURSEQ               numeric(5,0),
  CONDAT               date,
  EXPDAT               date,
  FRETERPO             varchar(10),
  FOLUP                varchar(1)
);