-- dbo.k11_tab  (2237868 rows)
CREATE TABLE dbo.k11_tab (
  idnk11_k11           int NOT NULL,
  uptime_k11           datetime NOT NULL,
  upname_k11           char(10) NOT NULL,
  idnk09_k11           int NOT NULL,
  idnk10_k11           int NOT NULL,
  idnk08_k11           int NOT NULL,
  idnk21_k11           int NOT NULL,
  checkd_k11           char(1) NOT NULL,
  itemno_k11           int NOT NULL,
  doccnt_k11           int NOT NULL,
  hittyp_k11           char(10) NOT NULL,
  pr_num_k11           char(30) NOT NULL,
  closes_k11           datetime NOT NULL,
  solqty_k11           int NOT NULL,
  sol_um_k11           char(2) NOT NULL,
  our_pn_k11           char(32) NOT NULL,
  estval_k11           numeric(10,2) NOT NULL,
  dwgamc_k11           char(1) NOT NULL,
  acqdes_k11           char(60) NOT NULL,
  amcdes_k11           char(40) NOT NULL,
  u_name_k11           char(10) NOT NULL,
  clndry_k11           char(1) NOT NULL,
  cshmat_k11           char(2) NOT NULL,
  cshthk_k11           char(1) NOT NULL,
  intcnt_k11           char(2) NOT NULL,
  incqty_k11           char(3) NOT NULL,
  lvlprs_k11           char(1) NOT NULL,
  opicod_k11           char(1) NOT NULL,
  pakcod_k11           char(1) NOT NULL,
  paklvl_k11           char(1) NOT NULL,
  prsmth_k11           char(2) NOT NULL,
  prsmat_k11           char(2) NOT NULL,
  untcnt_k11           char(2) NOT NULL,
  wrpmat_k11           char(2) NOT NULL,
  qupcod_k11           char(3) NOT NULL,
  mrkcod_k11           char(50) NOT NULL,
  mrkacr_k11           char(20) NOT NULL,
  pkgdta_k11           char(50) NOT NULL,
  seldes_k11           char(30) NOT NULL,
  picode_k11           char(1) NOT NULL,
  amcode_k11           char(2) NOT NULL,
  lxtnam_k11           char(15) NOT NULL,
  lam_id_k11           int NOT NULL,
  prdqty_k11           int NOT NULL DEFAULT ((0)),
  fatqty_k11           int NOT NULL DEFAULT ((0)),
  optqty_k11           int NOT NULL DEFAULT ((0)),
  othqty_k11           int NOT NULL DEFAULT ((0)),
  fobcod_k11           char(1) NOT NULL DEFAULT (''),
  PRIMARY KEY (idnk11_k11)
);